### ISSUE TITLE
Clip to bounds

### ISSUE THREAD

**Issue by oyapici** [JanHalozan/SFFullscreenImageDetailViewController#1]
Hello,
This is a great work.  Can you help me how can I display whole image without clipping. If I change view.clipsToBounds = false ;
1- The image doesn't fit the screen, 
2- Image returns original location as square and then change to circle. 

Your help really appreciated.

Thank you.

**Comment by JanHalozan** [comment]
Hi,

can you provide me with a bit more detail please? Here are a few things that come to mind:

1. try setting the `contentMode` of the image view that you pass when creating the FullscreenImageDetailViewController to `scaleAspectFit` or `scaleAspectFill`.

2. Yes this is definitely a bug. Will fix it and will let you know when I'm done.

Ok?

**Comment by oyapici** [comment]
Hi,

Actually, I have added view.contentMode = UIViewContentMode.ScaleAspectFit in init (imageView view: UIImageView)   and it worked.  

Thank you

**Comment by JanHalozan** [comment]
Ok great.

As for the rounded corners I will fix it and let you know when it's done.

**Comment by JanHalozan** [comment]
Ok I tested applying an image corner radius to the origin image view and it seems that is works fine.

Can you explain this in a bit more detail:
`2- Image returns original location as square and then change to circle.`?

Thanks.

**Comment by oyapici** [comment]
Thank you su much.
